version: '3'
services:
    oracle:
        container_name: oracledb
        image: store/oracle/database-enterprise:12.2.0.1
        shm_size: 4096M
        volumes:
            - "oracle_db:/u01/app/oracle/oradata"
            - "./docker/oracle/startup_scripts:/u01/app/oracle/scripts/startup"
        ports:
            - 1521:1521
            - 8080:8080
        environment:
            - ORACLE_ALLOW_REMOTE=true
            - ORACLE_PWD=PWD

volumes: 
    oracle_db:
